version: 2

project_name: ozsh

builds:
  - id: ozsh
    main: ./cmd/ozsh
    binary: ozsh
    env:
      - CGO_ENABLED=0
    flags:
      - -buildvcs=false
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - android
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: android
        goarch: amd64

archives:
  - formats: [tar.gz]

checksum:
  name_template: checksums.txt

signs:
  - artifacts: checksum
    cmd: cosign
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - --bundle=${artifact}.bundle
      - ${artifact}

release:
  extra_files:
    - glob: ./dist/checksums.txt.bundle

changelog:
  sort: asc
  use: github
