services:
  ozsh:
    build:
      context: .
    image: ${GHCR_IMAGE:-ghcr.io/snakepilot10/ozsh}:local
    command: ["version"]
    environment:
      APP_ENV: ${APP_ENV:-local}
    healthcheck:
      test: ["CMD", "ozsh", "version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
