package prompt

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/snakepilot10/ozsh/internal/config"
)

// Generate renders a prompt from an isolated copy of cfg. Generation fills in
// legacy defaults, so mutating the caller's active TUI/config state here would
// create hard-to-reproduce side effects after preview or apply operations.
func Generate(cfg *config.Config) (string, error) {
	cfg = cloneConfig(cfg)
	config.FillDefaults(cfg)
	if rendered, ok, err := generateFromTemplate(cfg); ok || err != nil {
		return rendered, err
	}

	var b strings.Builder
	b.WriteString("# Generated by ozsh. Do not edit manually.\n\n")
	b.WriteString("autoload -Uz colors && colors\n\n")
	if usesHexColor(cfg) {
		b.WriteString(`ozsh_color() {
  local hex="$1"
  local fallback="$2"
  if [[ "$COLORTERM" == *truecolor* || "$COLORTERM" == *24bit* ]]; then
    print -r -- "%F{${hex}}"
  else
    print -r -- "%F{${fallback}}"
  fi
}
`)
		b.WriteString("\n")
	}
	genHeader(&b, cfg)
	genPluginSources(&b, cfg)

	if segmentEnabled(cfg, "git") {
		b.WriteString(`ozsh_git_branch() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return
  local branch
  branch="$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)"
  [[ -n "$branch" ]] && echo "$branch"
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "venv") {
		b.WriteString(`ozsh_venv_name() {
  [[ -n "$VIRTUAL_ENV" ]] || return
  echo "${VIRTUAL_ENV:t}"
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "node") {
		b.WriteString(`ozsh_node_version() {
  [[ -f package.json ]] || return
  command -v node >/dev/null 2>&1 || return
  node --version 2>/dev/null
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "go") {
		b.WriteString(`ozsh_go_version() {
  [[ -f go.mod ]] || return
  command -v go >/dev/null 2>&1 || return
  go version 2>/dev/null | awk '{print $3}'
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "battery") {
		b.WriteString(`ozsh_battery_level() {
  local capacity=""
  if [[ -r /sys/class/power_supply/BAT0/capacity ]]; then
    capacity="$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null)"
  elif command -v termux-battery-status >/dev/null 2>&1; then
    capacity="$(termux-battery-status 2>/dev/null | sed -n 's/.*"percentage":[[:space:]]*\([0-9]\+\).*/\1/p')"
  fi
  [[ -n "$capacity" ]] && echo "${capacity}%"
}
`)
		b.WriteString("\n")
	}

	b.WriteString("ozsh_prompt() {\n")
	b.WriteString("  local last_status=\"$?\"\n")
	b.WriteString("  local parts=()\n")
	b.WriteString("  local right_parts=()\n\n")
	for _, name := range cfg.Prompt.Order {
		seg, ok := cfg.Prompt.Segments[name]
		if !ok || !segmentActive(cfg, name, seg) {
			continue
		}
		genSegment(&b, "parts", name, seg)
	}
	for _, name := range cfg.Prompt.RightOrder {
		seg, ok := cfg.Prompt.Segments[name]
		if !ok || !segmentActive(cfg, name, seg) {
			continue
		}
		genSegment(&b, "right_parts", name, seg)
	}

	b.WriteString("\n")
	sep := zshPromptSeparator(cfg.Prompt.Separator)
	if cfg.Prompt.Newline {
		fmt.Fprintf(&b, "  PROMPT=\"${(j:%s:)parts}\n❯ \"\n", sep)
	} else {
		fmt.Fprintf(&b, "  PROMPT=\"${(j:%s:)parts} ❯ \"\n", sep)
	}
	if cfg.Prompt.RightPrompt || len(cfg.Prompt.RightOrder) > 0 {
		fmt.Fprintf(&b, "  RPROMPT=\"${(j:%s:)right_parts}\"\n", sep)
	}
	b.WriteString("}\n\nprecmd_functions+=(ozsh_prompt)\n")
	return b.String(), nil
}

func cloneConfig(cfg *config.Config) *config.Config {
	if cfg == nil {
		return config.Default()
	}
	clone := *cfg
	clone.Prompt.Order = append([]string(nil), cfg.Prompt.Order...)
	clone.Prompt.RightOrder = append([]string(nil), cfg.Prompt.RightOrder...)
	clone.Prompt.Segments = make(map[string]config.SegmentConfig, len(cfg.Prompt.Segments))
	for name, segment := range cfg.Prompt.Segments {
		clone.Prompt.Segments[name] = segment
	}
	clone.Plugins.Items = append([]config.PluginItem(nil), cfg.Plugins.Items...)
	return &clone
}

func genSegment(b *strings.Builder, target, name string, cfg config.SegmentConfig) {
	switch name {
	case "user":
		fmt.Fprintf(b, "  %s+=(\"%s%s%%n%s%%f\")\n", target, fgOpen(cfg.FG), boldOpen(cfg.Bold), boldClose(cfg.Bold))
	case "cwd":
		fmt.Fprintf(b, "  %s+=(\"%s%%~%%f\")\n", target, fgOpen(cfg.FG))
	case "git":
		fmt.Fprintf(b, `  local git_branch
  git_branch="$(ozsh_git_branch)"
  [[ -n "$git_branch" ]] && %s+=("%s${git_branch}%%f")
`, target, fgOpen(cfg.FG))
	case "status":
		if cfg.ShowSuccess {
			fmt.Fprintf(b, `  if [[ "$last_status" == "0" ]]; then
    %s+=("%s%s✓%s%%f")
  else
    %s+=("%s%s✘ ${last_status}%s%%f")
  fi
`, target, fgOpen(cfg.FG), boldOpen(cfg.Bold), boldClose(cfg.Bold), target, fgOpen(cfg.FG), boldOpen(cfg.Bold), boldClose(cfg.Bold))
		} else {
			fmt.Fprintf(b, `  if [[ "$last_status" != "0" ]]; then
    %s+=("%s%s✘ ${last_status}%s%%f")
  fi
`, target, fgOpen(cfg.FG), boldOpen(cfg.Bold), boldClose(cfg.Bold))
		}
	case "time":
		fmt.Fprintf(b, "  %s+=(\"%s%%*%%f\")\n", target, fgOpen(cfg.FG))
	case "host":
		fmt.Fprintf(b, "  %s+=(\"%s%%m%%f\")\n", target, fgOpen(cfg.FG))
	case "venv":
		fmt.Fprintf(b, `  local venv_name
  venv_name="$(ozsh_venv_name)"
  [[ -n "$venv_name" ]] && %s+=("%s${venv_name}%%f")
`, target, fgOpen(cfg.FG))
	case "node":
		fmt.Fprintf(b, `  local node_version
  node_version="$(ozsh_node_version)"
  [[ -n "$node_version" ]] && %s+=("%s${node_version}%%f")
`, target, fgOpen(cfg.FG))
	case "go":
		fmt.Fprintf(b, `  local go_version
  go_version="$(ozsh_go_version)"
  [[ -n "$go_version" ]] && %s+=("%s${go_version}%%f")
`, target, fgOpen(cfg.FG))
	case "battery":
		fmt.Fprintf(b, `  local battery_level
  battery_level="$(ozsh_battery_level)"
  [[ -n "$battery_level" ]] && %s+=("%s${battery_level}%%f")
`, target, fgOpen(cfg.FG))
	case "jobs":
		fmt.Fprintf(b, `  local job_count
  job_count="$(jobs -p 2>/dev/null | wc -l | tr -d ' ')"
  if [[ "$job_count" != "0" ]]; then
    %s+=("%s${job_count} jobs%%f")
  fi
`, target, fgOpen(cfg.FG))
	}
}

func genHeader(b *strings.Builder, cfg *config.Config) {
	if !cfg.Header.Enabled {
		return
	}
	color := fgOpen(cfg.Theme.Accent)
	text := strconv.Quote(color + cfg.Header.Text + "%f")
	switch cfg.Header.Style {
	case "figlet":
		plainText := strconv.Quote(cfg.Header.Text)
		fmt.Fprintf(b, `if command -v figlet >/dev/null 2>&1; then
  figlet %s | while IFS= read -r line; do print -P "%s${line}%%f"; done
else
  print -P %s
fi

`, plainText, color, text)
	default:
		fmt.Fprintf(b, "print -P %s\n\n", text)
	}
}

func genPluginSources(b *strings.Builder, cfg *config.Config) {
	helperWritten := false
	for _, plugin := range cfg.Plugins.Items {
		if !plugin.Enabled || !plugin.Trusted {
			continue
		}
		source, ok := pluginSourcePath(plugin)
		if !ok {
			continue
		}
		if !helperWritten {
			b.WriteString(`ozsh_source_plugin() {
  local plugin_file="$1"
  local home_prefix="${HOME:A}/"
  local resolved="${plugin_file:A}"
  [[ "$resolved" == "$home_prefix"* ]] || return
  [[ -f "$resolved" && -r "$resolved" && ! -L "$resolved" ]] || return
  [[ "$resolved" != */../* ]] || return
  source "$resolved"
}
`)
			b.WriteString("\n")
			helperWritten = true
		}
		fmt.Fprintf(b, "ozsh_source_plugin %s\n", strconv.Quote(source))
	}
	if helperWritten {
		b.WriteString("\n")
	}
}

// pluginSourcePath never returns a plugin directory. A shell can only source a
// concrete, relative .zsh/.sh file under the plugin root.
func pluginSourcePath(plugin config.PluginItem) (string, bool) {
	load := strings.TrimSpace(plugin.Load)
	if load == "" || filepath.IsAbs(load) {
		return "", false
	}
	clean := filepath.Clean(load)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", false
	}
	ext := strings.ToLower(filepath.Ext(clean))
	if ext != ".zsh" && ext != ".sh" {
		return "", false
	}
	return filepath.Join(plugin.Source, clean), true
}

func generateFromTemplate(cfg *config.Config) (string, bool, error) {
	path := filepath.Join("templates", cfg.Prompt.Style+".zsh.tmpl")
	if _, err := os.Stat(path); err != nil {
		return "", false, nil
	}
	tmpl, err := template.ParseFiles(path)
	if err != nil {
		return "", true, fmt.Errorf("failed to parse template: %w", err)
	}
	var b strings.Builder
	if err := tmpl.Execute(&b, cfg); err != nil {
		return "", true, fmt.Errorf("failed to execute template: %w", err)
	}
	return b.String(), true, nil
}

func segmentEnabled(cfg *config.Config, name string) bool {
	segment, ok := cfg.Prompt.Segments[name]
	return ok && segmentActive(cfg, name, segment)
}

func segmentActive(cfg *config.Config, name string, segment config.SegmentConfig) bool {
	return segment.Enabled && (!cfg.Prompt.DisableHeavySegments || !isHeavySegment(name))
}

func isHeavySegment(name string) bool {
	switch name {
	case "git", "node", "go", "battery":
		return true
	default:
		return false
	}
}

func fgOpen(color string) string {
	if strings.HasPrefix(color, "#") {
		return "$(ozsh_color " + strconv.Quote(color) + " " + strconv.Quote(fallbackColor(color)) + ")"
	}
	return "%F{" + color + "}"
}

func zshPromptSeparator(separator string) string { return strings.ReplaceAll(separator, ":", "\\:") }

func usesHexColor(cfg *config.Config) bool {
	for _, segment := range cfg.Prompt.Segments {
		if strings.HasPrefix(segment.FG, "#") || strings.HasPrefix(segment.BG, "#") {
			return true
		}
	}
	for _, color := range []string{cfg.Theme.Accent, cfg.Theme.Success, cfg.Theme.Warning, cfg.Theme.Error} {
		if strings.HasPrefix(color, "#") {
			return true
		}
	}
	return false
}

func fallbackColor(hex string) string {
	switch strings.ToLower(hex) {
	case "#ff003c":
		return "red"
	case "#00ff9f":
		return "green"
	case "#ffe600":
		return "yellow"
	case "#6b6b80":
		return "white"
	default:
		return "cyan"
	}
}

func boldOpen(b bool) string {
	if b {
		return "%B"
	}
	return ""
}

func boldClose(b bool) string {
	if b {
		return "%b"
	}
	return ""
}
