package prompt

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/snakepilot10/ozsh/internal/config"
)

// Generate renders a prompt from an isolated copy of cfg.
func Generate(cfg *config.Config) (string, error) {
	cfg = cloneConfig(cfg)
	if err := config.Validate(cfg); err != nil {
		return "", fmt.Errorf("invalid config: %w", err)
	}
	var b strings.Builder
	b.WriteString("# Generated by ozsh. Do not edit manually.\n\n")
	b.WriteString("autoload -Uz colors && colors\n\n")
	if usesHexColor(cfg) {
		b.WriteString(`ozsh_color() {
  local hex="$1"
  local fallback="$2"
  if [[ "$COLORTERM" == *truecolor* || "$COLORTERM" == *24bit* ]]; then
    print -r -- "%F{${hex}}"
  else
    print -r -- "%F{${fallback}}"
  fi
}

ozsh_bg_color() {
  local hex="$1"
  local fallback="$2"
  if [[ "$COLORTERM" == *truecolor* || "$COLORTERM" == *24bit* ]]; then
    print -r -- "%K{${hex}}"
  else
    print -r -- "%K{${fallback}}"
  fi
}
`)
		b.WriteString("\n")
	}
	b.WriteString(`ozsh_join() {
  local sep="$1"
  shift
  local out=""
  local part
  local first=1
  for part in "$@"; do
    if (( first )); then
      first=0
    else
      out+="$sep"
    fi
    out+="$part"
  done
  print -r -- "$out"
}

ozsh_prompt_text() {
  local text="$1"
  local prompt_dollar='${ozsh_dollar}'
  local prompt_backtick='${ozsh_backtick}'
  text=${text//[[:cntrl:]]/}
  if [[ -o prompt_subst ]]; then
    text=${text//\$/$prompt_dollar}
    text=${text//\` + "`" + `/$prompt_backtick}
  fi
  if [[ -o prompt_percent ]]; then
    text=${text//\\/\\\\}
    text=${text//\%/%%}
  fi
  if [[ -o prompt_bang ]]; then
    text=${text//\!/!!}
  fi
  print -r -- "$text"
}

ozsh_prompt_text_from_stdin() {
  local text
  text="$(cat)"
  ozsh_prompt_text "$text"
}

ozsh_dollar='$'
ozsh_backtick='` + "`" + `'
`)
	b.WriteString("\n")
	genPluginSources(&b, cfg)

	if segmentEnabled(cfg, "git") {
		b.WriteString(`ozsh_git_branch() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return
  local branch
  branch="$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)"
  if [[ -n "$branch" ]] && [[ -n "$(git status --porcelain --untracked-files=no 2>/dev/null)" ]]; then
    branch+=" +"
  fi
  [[ -n "$branch" ]] && echo "$branch"
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "venv") {
		b.WriteString(`ozsh_venv_name() {
  [[ -n "$VIRTUAL_ENV" ]] || return
  echo "${VIRTUAL_ENV:t}"
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "node") {
		b.WriteString(`ozsh_node_version() {
  [[ -f package.json ]] || return
  command -v node >/dev/null 2>&1 || return
  node --version 2>/dev/null
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "go") {
		b.WriteString(`ozsh_go_version() {
  [[ -f go.mod ]] || return
  command -v go >/dev/null 2>&1 || return
  go version 2>/dev/null | awk '{print $3}'
}
`)
		b.WriteString("\n")
	}
	if segmentEnabled(cfg, "battery") {
		b.WriteString(`ozsh_battery_level() {
  local capacity=""
  if [[ -r /sys/class/power_supply/BAT0/capacity ]]; then
    capacity="$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null)"
  elif command -v termux-battery-status >/dev/null 2>&1; then
    capacity="$(termux-battery-status 2>/dev/null | sed -n 's/.*"percentage":[[:space:]]*\([0-9]\+\).*/\1/p')"
  fi
  [[ -n "$capacity" ]] && echo "${capacity}%"
}
`)
		b.WriteString("\n")
	}

	b.WriteString("ozsh_prompt() {\n")
	b.WriteString("  local last_status=\"$?\"\n")
	b.WriteString("  local parts=()\n")
	b.WriteString("  local right_parts=()\n\n")
	for _, name := range cfg.Prompt.Order {
		seg, ok := cfg.Prompt.Segments[name]
		if !ok || !segmentActive(cfg, name, seg) {
			continue
		}
		genSegment(&b, "parts", name, cfg.Prompt, seg)
	}
	for _, name := range cfg.Prompt.RightOrder {
		seg, ok := cfg.Prompt.Segments[name]
		if !ok || !segmentActive(cfg, name, seg) {
			continue
		}
		genSegment(&b, "right_parts", name, cfg.Prompt, seg)
	}

	b.WriteString("\n")
	fmt.Fprintf(&b, "  local ozsh_raw_separator=%s\n", zshSingleQuote(cfg.Prompt.Separator))
	b.WriteString("  local ozsh_separator\n")
	b.WriteString("  ozsh_separator=\"$(ozsh_prompt_text \"$ozsh_raw_separator\")\"\n")
	fmt.Fprintf(&b, "  local ozsh_symbol=\"$(ozsh_prompt_text %s)\"\n", zshSingleQuote(cfg.Prompt.Symbol+" "))
	if cfg.Prompt.Layout == config.PromptLayoutTwoLine {
		b.WriteString("  PROMPT=\"$(ozsh_join \"$ozsh_separator\" \"${parts[@]}\")\"$'\\n'\"${ozsh_symbol}\"\n")
	} else {
		b.WriteString("  PROMPT=\"$(ozsh_join \"$ozsh_separator\" \"${parts[@]}\") ${ozsh_symbol}\"\n")
	}
	if cfg.Prompt.RightPrompt || len(cfg.Prompt.RightOrder) > 0 {
		b.WriteString("  RPROMPT=\"$(ozsh_join \"$ozsh_separator\" \"${right_parts[@]}\")\"\n")
	} else {
		b.WriteString("  RPROMPT=\"\"\n")
	}
	b.WriteString("}\n\nif (( ${precmd_functions[(Ie)ozsh_prompt]:-0} == 0 )); then\n  precmd_functions+=(ozsh_prompt)\nfi\n")
	return b.String(), nil
}

func cloneConfig(cfg *config.Config) *config.Config {
	if cfg == nil {
		return config.Default()
	}
	clone := *cfg
	clone.Prompt.Order = append([]string(nil), cfg.Prompt.Order...)
	clone.Prompt.RightOrder = append([]string(nil), cfg.Prompt.RightOrder...)
	clone.Prompt.Segments = make(map[string]config.SegmentConfig, len(cfg.Prompt.Segments))
	for name, segment := range cfg.Prompt.Segments {
		clone.Prompt.Segments[name] = segment
	}
	clone.Plugins.Selected = append([]string(nil), cfg.Plugins.Selected...)
	clone.Plugins.Items = append([]config.PluginItem(nil), cfg.Plugins.Items...)
	return &clone
}

func genSegment(b *strings.Builder, target, name string, promptConfig config.PromptConfig, cfg config.SegmentConfig) {
	open := styleOpen(cfg)
	close := styleClose(cfg)
	prefix := ""
	if icon := segmentIcon(promptConfig, cfg); icon != "" {
		iconVar := "ozsh_icon_" + target + "_" + name
		fmt.Fprintf(b, "  local %s\n", iconVar)
		fmt.Fprintf(b, "  %s=\"$(ozsh_prompt_text %s)\"\n", iconVar, zshSingleQuote(icon))
		prefix = "${" + iconVar + "} "
	}
	switch name {
	case "user":
		if promptConfig.DisplayName == "" {
			fmt.Fprintf(b, "  %s+=(\"%s%s%%n%s\")\n", target, open, prefix, close)
		} else {
			nameVar := "ozsh_display_name_" + target
			fmt.Fprintf(b, "  local %s\n", nameVar)
			fmt.Fprintf(b, "  %s=\"$(ozsh_prompt_text %s)\"\n", nameVar, zshSingleQuote(promptConfig.DisplayName))
			fmt.Fprintf(b, "  %s+=(\"%s%s${%s}%s\")\n", target, open, prefix, nameVar, close)
		}
	case "cwd":
		fmt.Fprintf(b, "  %s+=(\"%s%s%%~%s\")\n", target, open, prefix, close)
	case "git":
		fmt.Fprintf(b, `  local git_branch
  git_branch="$(ozsh_git_branch | ozsh_prompt_text_from_stdin)"
  [[ -n "$git_branch" ]] && %s+=("%s%s${git_branch}%s")
`, target, open, prefix, close)
	case "status":
		if cfg.ShowSuccess {
			fmt.Fprintf(b, `  if [[ "$last_status" == "0" ]]; then
    %s+=("%s%s✓%s")
  else
    %s+=("%s%s✘ ${last_status}%s")
  fi
`, target, open, prefix, close, target, open, prefix, close)
		} else {
			fmt.Fprintf(b, `  if [[ "$last_status" != "0" ]]; then
    %s+=("%s%s✘ ${last_status}%s")
  fi
`, target, open, prefix, close)
		}
	case "time":
		fmt.Fprintf(b, "  %s+=(\"%s%s%%*%s\")\n", target, open, prefix, close)
	case "host":
		fmt.Fprintf(b, "  %s+=(\"%s%s%%m%s\")\n", target, open, prefix, close)
	case "venv":
		fmt.Fprintf(b, `  local venv_name
  venv_name="$(ozsh_venv_name | ozsh_prompt_text_from_stdin)"
  [[ -n "$venv_name" ]] && %s+=("%s%s${venv_name}%s")
`, target, open, prefix, close)
	case "node":
		fmt.Fprintf(b, `  local node_version
  node_version="$(ozsh_node_version | ozsh_prompt_text_from_stdin)"
  [[ -n "$node_version" ]] && %s+=("%s%s${node_version}%s")
`, target, open, prefix, close)
	case "go":
		fmt.Fprintf(b, `  local go_version
  go_version="$(ozsh_go_version | ozsh_prompt_text_from_stdin)"
  [[ -n "$go_version" ]] && %s+=("%s%s${go_version}%s")
`, target, open, prefix, close)
	case "battery":
		fmt.Fprintf(b, `  local battery_level
  battery_level="$(ozsh_battery_level | ozsh_prompt_text_from_stdin)"
  [[ -n "$battery_level" ]] && %s+=("%s%s${battery_level}%s")
`, target, open, prefix, close)
	case "jobs":
		fmt.Fprintf(b, `  local job_count
  job_count="$(jobs -p 2>/dev/null | wc -l | tr -d ' ')"
  if [[ "$job_count" != "0" ]]; then
    %s+=("%s%s${job_count} jobs%s")
  fi
`, target, open, prefix, close)
	}
}

func segmentIcon(promptConfig config.PromptConfig, segment config.SegmentConfig) string {
	if promptConfig.IconMode == config.IconModeNerd && segment.NerdIcon != "" {
		return segment.NerdIcon
	}
	if segment.CompatibleIcon != "" {
		return segment.CompatibleIcon
	}
	return segment.Icon
}

func genPluginSources(b *strings.Builder, cfg *config.Config) {
	plugins := append([]config.PluginItem(nil), cfg.Plugins.Items...)
	sort.SliceStable(plugins, func(i, j int) bool {
		return pluginPriority(plugins[i].Name) < pluginPriority(plugins[j].Name)
	})
	helperWritten := false
	completionWritten := false
	for _, plugin := range plugins {
		if !plugin.Enabled || !plugin.Trusted {
			continue
		}
		source, ok := pluginSourcePath(plugin)
		if !ok {
			continue
		}
		if !helperWritten {
			b.WriteString(`ozsh_source_plugin() {
  local plugin_file="$1"
  local home_prefix="${HOME:A}/"
  local absolute="${plugin_file:a}"
  local resolved="${plugin_file:A}"
  [[ "$resolved" == "$home_prefix"* ]] || return
  [[ "$resolved" == "$absolute" ]] || return
  [[ -f "$resolved" && -r "$resolved" && ! -L "$resolved" ]] || return
  [[ "$resolved" != */../* ]] || return
  source "$resolved"
}
`)
			b.WriteString("\n")
			helperWritten = true
		}
		if plugin.Name == "fzf-tab" && !completionWritten {
			b.WriteString("autoload -Uz compinit && compinit\n")
			completionWritten = true
		}
		fmt.Fprintf(b, "ozsh_source_plugin %s\n", zshSingleQuote(source))
	}
	if helperWritten {
		b.WriteString("\n")
	}
}

func pluginPriority(name string) int {
	switch name {
	case "zsh-autosuggestions":
		return 0
	case "fzf-tab":
		return 1
	case "zsh-syntax-highlighting":
		return 3
	default:
		return 2
	}
}

func pluginSourcePath(plugin config.PluginItem) (string, bool) {
	load := strings.TrimSpace(plugin.Load)
	if load == "" || filepath.IsAbs(load) {
		return "", false
	}
	clean := filepath.Clean(load)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", false
	}
	ext := strings.ToLower(filepath.Ext(clean))
	if ext != ".zsh" && ext != ".sh" {
		return "", false
	}
	return filepath.Join(plugin.Source, clean), true
}

func zshSingleQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func segmentEnabled(cfg *config.Config, name string) bool {
	segment, ok := cfg.Prompt.Segments[name]
	return ok && segmentActive(cfg, name, segment)
}

func segmentActive(cfg *config.Config, name string, segment config.SegmentConfig) bool {
	return segment.Enabled && (!cfg.Prompt.DisableHeavySegments || !isHeavySegment(name))
}

func isHeavySegment(name string) bool {
	switch name {
	case "git", "node", "go", "battery":
		return true
	default:
		return false
	}
}

func fgOpen(color string) string {
	if strings.HasPrefix(color, "#") {
		return "$(ozsh_color " + strconv.Quote(color) + " " + strconv.Quote(fallbackColor(color)) + ")"
	}
	return "%F{" + color + "}"
}

func bgOpen(color string) string {
	if color == "" || color == "default" {
		return ""
	}
	if strings.HasPrefix(color, "#") {
		return "$(ozsh_bg_color " + strconv.Quote(color) + " " + strconv.Quote(fallbackColor(color)) + ")"
	}
	return "%K{" + color + "}"
}

func styleOpen(cfg config.SegmentConfig) string {
	return bgOpen(cfg.BG) + fgOpen(cfg.FG) + boldOpen(cfg.Bold)
}

func styleClose(cfg config.SegmentConfig) string {
	close := boldClose(cfg.Bold) + "%f"
	if cfg.BG != "" && cfg.BG != "default" {
		close += "%k"
	}
	return close
}

func usesHexColor(cfg *config.Config) bool {
	for _, segment := range cfg.Prompt.Segments {
		if strings.HasPrefix(segment.FG, "#") || strings.HasPrefix(segment.BG, "#") {
			return true
		}
	}
	for _, color := range []string{cfg.Theme.Accent, cfg.Theme.Success, cfg.Theme.Warning, cfg.Theme.Error} {
		if strings.HasPrefix(color, "#") {
			return true
		}
	}
	return false
}

func fallbackColor(hex string) string {
	switch strings.ToLower(hex) {
	case "#ff003c":
		return "red"
	case "#00ff9f":
		return "green"
	case "#ffe600":
		return "yellow"
	case "#6b6b80":
		return "white"
	default:
		return "cyan"
	}
}

func boldOpen(b bool) string {
	if b {
		return "%B"
	}
	return ""
}

func boldClose(b bool) string {
	if b {
		return "%b"
	}
	return ""
}
