package config

func Default() *Config {
	return &Config{
		Version: CurrentConfigVersion,
		Prompt: PromptConfig{
			Style:                "simple",
			Newline:              true,
			RightPrompt:          false,
			DisableHeavySegments: false,
			Separator:            "  ",
			Order: []string{
				"user", "cwd", "git", "status", "execution_time", "venv", "python",
				"node", "go", "rust", "battery", "jobs", "host", "time",
			},
			RightOrder:     []string{},
			TransientOrder: []string{"status", "cwd"},
			Segments: map[string]SegmentConfig{
				"user": {
					Enabled: true,
					Icon:    "",
					FG:      "cyan",
					BG:      "",
					Bold:    true,
				},
				"cwd": {
					Enabled: true,
					Icon:    "",
					FG:      "yellow",
					BG:      "",
					Bold:    false,
				},
				"git": {
					Enabled: true,
					Icon:    "",
					FG:      "magenta",
					BG:      "",
					Bold:    false,
				},
				"status": {
					Enabled:     true,
					Icon:        "",
					FG:          "red",
					BG:          "",
					Bold:        true,
					ShowSuccess: false,
				},
				"time": {
					Enabled: false,
					Icon:    "",
					FG:      "blue",
					BG:      "",
					Bold:    false,
				},
				"host": {
					Enabled: false,
					Icon:    "",
					FG:      "cyan",
					BG:      "",
					Bold:    false,
				},
				"venv": {
					Enabled: false,
					Icon:    "",
					FG:      "green",
					BG:      "",
					Bold:    false,
				},
				"node": {
					Enabled: false,
					Icon:    "",
					FG:      "green",
					BG:      "",
					Bold:    false,
				},
				"go": {
					Enabled: false,
					Icon:    "",
					FG:      "cyan",
					BG:      "",
					Bold:    false,
				},
				"battery": {
					Enabled: false,
					Icon:    "",
					FG:      "yellow",
					BG:      "",
					Bold:    false,
				},
				"jobs": {
					Enabled: false,
					Icon:    "",
					FG:      "magenta",
					BG:      "",
					Bold:    false,
				},
				"execution_time": {
					Enabled: false,
					FG:      "yellow",
				},
				"python": {
					Enabled:  false,
					FG:       "yellow",
					CacheTTL: 30,
				},
				"rust": {
					Enabled:  false,
					FG:       "red",
					CacheTTL: 30,
				},
			},
		},
		Plugins: PluginConfig{
			Engine: "manual",
			Items:  []PluginItem{},
		},
		Theme: ThemeConfig{
			Name:        "cyber-cyan",
			Description: "High-contrast cyan theme",
			Tier:        "unicode",
			Requires:    []string{"unicode"},
			Accent:      "#00f5ff",
			Background:  "#09090d",
			Muted:       "#6b6b80",
			Success:     "#00ff9f",
			Warning:     "#ffe600",
			Error:       "#ff003c",
		},
	}
}
