package config

var Presets = map[string]ThemeConfig{
	"cyber-cyan": {
		Name:        "cyber-cyan",
		Description: "High-contrast cyan theme",
		Tier:        "unicode",
		Requires:    []string{"unicode"},
		Accent:      "#00f5ff",
		Background:  "#09090d",
		Muted:       "#6b6b80",
		Success:     "#00ff9f",
		Warning:     "#ffe600",
		Error:       "#ff003c",
	},
	"neon-red": {
		Name:        "neon-red",
		Description: "Dark theme with neon red accents",
		Tier:        "unicode",
		Requires:    []string{"unicode"},
		Accent:      "#ff003c",
		Background:  "#09090d",
		Muted:       "#6b6b80",
		Success:     "#00ff9f",
		Warning:     "#ffe600",
		Error:       "#ff003c",
	},
	"matrix-green": {
		Name:        "matrix-green",
		Description: "Dark theme with terminal green accents",
		Tier:        "unicode",
		Requires:    []string{"unicode"},
		Accent:      "#00ff9f",
		Background:  "#050807",
		Muted:       "#6b806f",
		Success:     "#00ff9f",
		Warning:     "#ffe600",
		Error:       "#ff003c",
	},
}
